name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, closed]
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Get Playwright Browser versions
      run: |
        PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | head -n1 | sed 's/.*@//')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
    - uses: actions/cache@v3
      id: playwright-cache
      with:
        path: '~/.cache/ms-playwright'
        key: '${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}'
        # As a fallback, if the Playwright version has changed, try use the
        # most recently cached version. There's a good chance that at least one
        # of the browser binary versions haven't been updated, so Playwright can
        # skip installing that in the next step.
        # Note: When falling back to an old cache, `cache-hit` (used below)
        # will be `false`. This allows us to restore the potentially out of
        # date cache, but still let Playwright decide if it needs to download
        # new binaries or not.
        restore-keys: |
          ${{ runner.os }}-playwright-
      # If the Playwright browser binaries weren't able to be restored, we tell
      # paywright to install everything for us.
    - name: Install Playwright Browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
